### ISSUE TITLE
No such module 'RNShareMenu'

### ISSUE THREAD

**Issue by Larens94** [Expensify/react-native-share-menu#144]
hi, i find this error on xcode, how can i fix it?

<img width="714" alt="Schermata 2021-08-02 alle 11 03 55" src="https://user-images.githubusercontent.com/32598073/127834840-c354b7cc-1dd9-463c-83c1-546a3fca0842.png">

**Comment by aliosmankepir** [comment]
Same problem.

**Comment by sospedra** [comment]
same issue, couldn't find a workaround

**Comment by HugoGresse** [comment]
The issues seems to come from misaligned Deployment Target. 

Those 4 needs to match:
- App target
- App Project
- ShareExtension target
- Podfile `platform :ios, '11.0'` 

<img width="683" alt="Capture d’écran 2021-09-09 à 14 22 48" src="https://user-images.githubusercontent.com/662377/132685110-b0f741b1-8a84-4017-a55d-26c3d0a6a103.png">
<img width="689" alt="Capture d’écran 2021-09-09 à 14 22 30" src="https://user-images.githubusercontent.com/662377/132685122-ab2a9e3a-64f5-45c2-a3d5-f81c6d262393.png">

**Comment by callaars** [comment]
Mine are all on 11.0 and this doesn't seem to resolve this issue.

**Comment by HugoGresse** [comment]
> Mine are all on 11.0 and this doesn't seem to resolve this issue.

did you check all 4?

**Comment by callaars** [comment]
Yes, but for me, I just checked it was the Podfile not being correct. A recent git merge removed the additional code for me. I'm referring to this:

```
  post_install do |installer| react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end

target 'SHARE_EXTENSION' do
  use_react_native!(
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  # Manually link packages here to keep your extension bundle size minimal
end
```

This is resolved for me :)

**Comment by lukebrandonfarrell** [comment]
I fixed this after a full day of searching on a Mac M1:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '$(inherited)'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
```

**Comment by tchapi** [comment]
Hi all
I've tried all the workarounds here, and none work, I'm still stuck without being able to build with the same error as the OP

```
/.../node_modules/react-native-share-menu/ios/ReactShareViewController.swift:10:8: error: no such module 'RNShareMenu'
import RNShareMenu
       ^
```

This is the case when building with the command line _as well as_ building within XCode

Any hints ?
- - -
Xcode: 13.3.1
M1 Pro

**Comment by i6mi6** [comment]
Increasing deployment targets to 11.0 on both the main project AND the share extension finally worked for me

**Comment by anatooly** [comment]
I have this problem too on last 6.0.0
<img width="960" alt="image" src="https://user-images.githubusercontent.com/317380/185487991-fbdfa3e2-6d5c-41f8-ac31-f39240f22406.png">
```
<unknown>:0: error: module map file '/Users/username/Library/Developer/Xcode/DerivedData/Projectname-fstvewgwphvmyzbeiiueojksdirp/Build/Products/Debug-iphoneos/RNShareMenu/RNShareMenu.modulemap' not found
Command PrecompileSwiftBridgingHeader emitted errors but did not return a nonzero exit code to indicate failure
```

Solution: I find my mistake open *.xcodeproj, but need *.xcworkspace :-)

**Comment by viktorRot** [comment]
Unfortunately nothing helped so far for me. I was able to resolve "No such module 'RNShareMenu' " error by starting Xcode with "Rosetta".

But I still receive the two errors: "RNShareMenu.modulemap'" not found and "Command SwiftGeneratePch emitted errors but did not return a nonzero exit code to indicate failure".

Does someone has any idea? 

IOS 13.0.1
Xcode 14.1
M1 Pro

Thanks in advance

**Comment by alxmhe** [comment]
I also encounter the error as described by @viktorRot, and have been unable to fix it so far. I tried everything in this thread.
Any new idea?

**Comment by aw-geoop** [comment]
Same issue, any solution yet?

**Comment by YasirAliSmit** [comment]
i have been this issue any solution avaible
